language: ruby

sudo: required

dist: buster

rvm:
  - 2.4.6

services:
  - docker

cache:
  directories:
   - vendor/.bundle

install:
    - sudo ./scripts/install-deps.sh
    - bundle install --path vendor/.bundle

jobs:
  include:
    - name: "Exporter Tests"
      script: bundle exec rspec
    - name: "Docker Build"
      script: docker build . -t lib-mapknitter-exporter:latest